name: FeedBot
on:
  schedule:
    # L채uft alle 5 Minuten - anpassbar 체ber https://crontab.guru/
    - cron: '*/5 * * * *'
  workflow_dispatch: # Erlaubt manuelles Ausf체hren

concurrency:
  group: feedbot

jobs:
  rss-to-bluesky:
    runs-on: ubuntu-latest
    steps:
      - name: Generate cache key
        uses: actions/github-script@v6
        id: generate-key
        with:
          script: |
            core.setOutput('cache-key', new Date().valueOf())
            
      - name: Retrieve cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/blueskyfeedbot
          key: feed-cache-${{ steps.generate-key.outputs.cache-key }}
          restore-keys: feed-cache-
          
      - name: Post RSS to Bluesky
        uses: 'joschi/blueskyfeedbot@v1'
        with:
          # Ihr RSS Feed
          rss-feed: https://feeds.feedburner.com/AtomlaborWuppertalBlog
          # Template f체r die Posts
          template: '{{item.title}} {{item.link}}'
          # Ihr Bluesky Username (eigene Domain)
          username: ${{ secrets.BLUESKY_USERNAME }}
          # App-Passwort
          password: ${{ secrets.BLUESKY_PASSWORD }}
          # Cache-Datei Pfad
          cache-file: ${{ github.workspace }}/blueskyfeedbot/cache.json
          # Maximale Anzahl Posts beim ersten Lauf
          initial-post-limit: 10
